#!/bin/sh
cd dmenu &&  make && sudo make install clean && \
cd ../dwm &&  make && sudo make install clean && \
cd ../slock && make && sudo make install clean && \
cd ../st &&  sudo make install clean && cd ../tabbed && \
make && sudo make install clean
